import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import { Button, Card, Container, Modal } from "react-bootstrap";
import CommentInput from "../components/CommentInput";
import CommentListItem from "../components/CommentListItem";
import TaskCard from "../components/TaskCard";
import TaskStatusDropdown from "../components/TaskStatusDropdown";
import CommentDialog from "../components/CommentDialog";
import useFakeTasks from "../hooks/useFakeTasks";
import styles from "../styles/Home.module.css";
import UserListItem from "../components/UserListItem";
import UserListDialog from "../components/UserListDialog";

const Home: NextPage = () => {
  const fakeTasks = useFakeTasks();
  const [showCommentDialog, setShowCommentDialog] = useState(false);

  const [userListDialog, setUserListDialog] = useState(false);
  return (
    <Container className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {fakeTasks.map((props, i) => (
        <TaskCard {...props} key={i} />
      ))}
      <Button onClick={() => setShowCommentDialog(true)}>dsffds</Button>
      <Button onClick={() => setUserListDialog(true)}>dsffds</Button>
      <CommentDialog
        show={showCommentDialog}
        onHide={() => setShowCommentDialog(false)}
        centered
      />
      <UserListDialog
        show={userListDialog}
        onHide={() => setUserListDialog(false)}
        centered
      />
    </Container>
  );
};

export default Home;
